Repository PHPCSStandards/PHPCSDevTools, pull requests merged in 2025-05, with the labels that each got.

#173 Add FeatureComplete tests to phpunitlte9.xml.dist
  phpunitlte9.xml.dist
Labels: Type: chores/QA

#175 README: use the xmllint-validate action in the CI code sample
  README.md
Labels: Type: documentation, Feature: XML Documentation XSD

#177 GH Pages: fix website after markdown tweaks
  .remarkrc
  README.md
Labels: Type: documentation, Type: chores/QA

#178 Add pull request template
  .github/pull_request_template.md
Labels: Type: chores/QA

#179 GH Actions: split test jobs
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
Labels: Type: chores/QA

#181 README: minor tweak to XSD validate code sample
  README.md
Labels: Type: documentation, Feature: XML Documentation XSD

#183 GH Actions: add workflow to label PRs which are in a conflict state
  .github/workflows/label-merge-conflicts.yml
Labels: Type: chores/QA

#184 PHPCSDebug ruleset: update schema URL
  PHPCSDebug/ruleset.xml
Labels: Type: enhancement, Feature: PHPCSDebug ruleset
